/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Tender {
  'id' : bigint,
  'emd' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'deadline' : bigint,
  'eligibility' : string,
  'summary' : string,
  'category' : string,
  'department' : string,
  'riskReasons' : Array<string>,
  'budget' : string,
  'riskLevel' : string,
  'location' : string,
  'relevanceTags' : Array<string>,
}
export interface UserProfile {
  'turnover' : string,
  'savedTenders' : Array<bigint>,
  'name' : string,
  'experience' : bigint,
  'company' : string,
  'industry' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'categoryCounts' : Array<[string, bigint]>,
      'lowRiskCount' : bigint,
      'departmentCounts' : Array<[string, bigint]>,
      'totalTenders' : bigint,
      'mediumRiskCount' : bigint,
      'highRiskCount' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSavedTenders' : ActorMethod<[], Array<bigint>>,
  'getTenderById' : ActorMethod<[bigint], [] | [Tender]>,
  'getTenders' : ActorMethod<[], Array<Tender>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTender' : ActorMethod<[bigint], undefined>,
  'unsaveTender' : ActorMethod<[bigint], undefined>,
  'updateUserProfile' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];