/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'turnover' : IDL.Text,
  'savedTenders' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'experience' : IDL.Nat,
  'company' : IDL.Text,
  'industry' : IDL.Text,
});
export const Tender = IDL.Record({
  'id' : IDL.Nat,
  'emd' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'deadline' : IDL.Int,
  'eligibility' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
  'department' : IDL.Text,
  'riskReasons' : IDL.Vec(IDL.Text),
  'budget' : IDL.Text,
  'riskLevel' : IDL.Text,
  'location' : IDL.Text,
  'relevanceTags' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'categoryCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'lowRiskCount' : IDL.Nat,
          'departmentCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'totalTenders' : IDL.Nat,
          'mediumRiskCount' : IDL.Nat,
          'highRiskCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSavedTenders' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getTenderById' : IDL.Func([IDL.Nat], [IDL.Opt(Tender)], ['query']),
  'getTenders' : IDL.Func([], [IDL.Vec(Tender)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTender' : IDL.Func([IDL.Nat], [], []),
  'unsaveTender' : IDL.Func([IDL.Nat], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'turnover' : IDL.Text,
    'savedTenders' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'experience' : IDL.Nat,
    'company' : IDL.Text,
    'industry' : IDL.Text,
  });
  const Tender = IDL.Record({
    'id' : IDL.Nat,
    'emd' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'deadline' : IDL.Int,
    'eligibility' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
    'department' : IDL.Text,
    'riskReasons' : IDL.Vec(IDL.Text),
    'budget' : IDL.Text,
    'riskLevel' : IDL.Text,
    'location' : IDL.Text,
    'relevanceTags' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'categoryCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'lowRiskCount' : IDL.Nat,
            'departmentCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'totalTenders' : IDL.Nat,
            'mediumRiskCount' : IDL.Nat,
            'highRiskCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSavedTenders' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getTenderById' : IDL.Func([IDL.Nat], [IDL.Opt(Tender)], ['query']),
    'getTenders' : IDL.Func([], [IDL.Vec(Tender)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTender' : IDL.Func([IDL.Nat], [], []),
    'unsaveTender' : IDL.Func([IDL.Nat], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };